version: 0.2

phases:
  pre_builds:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_builds:
    commands:
      - aws s3 sync ${LOCAL_FILES} s3://${S3_BUCKET_NAME} --delete
 
artifacts:
  files:
    - '**/*'
 
  
      
      
      
      

